<?php

namespace AppBundle\Repository;

/**
 * BonusCardHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonusCardHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
