imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event]
        console:
            type:   console
            channels: [!event, !doctrine]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

bazinga_faker:
    orm: doctrine
    entities:
        AppBundle\AppBundle\Entity\BonusCard:
            number: 500
            custom_formatters:
                series:   { method: numberBetween, parameters: [ min = 100, max = 999 ] }
                number:   { method: numberBetween, parameters: [ min = 100000, max = 999999 ] }
                issueDate:   { method: dateTimeBetween,  parameters: [ startDate = '-2 year', max = 'now' ] }
                expDate:   { method: dateTimeInInterval,  parameters: [ startDate = 'now', max = '+2 year' ] }
                status:   { method: randomElement, parameters: [ [ 'active', 'inactive', 'expired' ] ] }
